#!/bin/bash
set -ex

docker-compose exec phpfpm bash -c "echo 'CREATE DATABASE ctoec;' | mysql -h mysql -u root -ppassword"
docker-compose exec phpfpm bash -c " echo \"CREATE USER 'wordpress'@'%' IDENTIFIED BY 'password';\" | mysql -h mysql -u root -ppassword"
docker-compose exec phpfpm bash -c "echo \" GRANT ALL PRIVILEGES ON  ctoec.* TO 'wordpress'@'%'; \" | mysql -h mysql -u root -ppassword"
docker run -it -u $(id -u):$(id -g) -v $(pwd):/wordpress 10up/phpfpm:7.3 bash -c "cd /wordpress && composer install"
docker-compose exec -u $(id -u):$(id -g) phpfpm bash -c 'wp config create --dbname=ctoec --dbuser=wordpress --dbhost=mysql --dbpass=password'
docker-compose exec phpfpm bash -c 'mysql -h mysql -u root -ppassword ctoec < /tmp/backup'
