#!/bin/sh
set -ex

docker-compose exec phpfpm bash -c 'mysql -h mysql -u root -ppassword ctoec < /tmp/backup/backup.sql'
docker-compose exec phpfpm bash -c " echo \"USE ctoec; UPDATE wp_options SET option_value='http://localhost:8080' WHERE option_name ='home';\" | mysql -h mysql -u root -ppassword"
docker-compose exec phpfpm bash -c " echo \"USE ctoec; UPDATE wp_options SET option_value='http://localhost:8080' WHERE option_name ='siteurl';\" | mysql -h mysql -u root -ppassword"