#!/bin/bash
set -ex

# Clean before reset
docker-compose exec phpfpm bash -c "rm wp-config.php || true"
docker-compose exec phpfpm bash -c "echo 'DROP DATABASE IF EXISTS ctoec;' | mysql -h mysql -u root -ppassword"
docker-compose exec phpfpm bash -c "echo 'DROP USER IF EXISTS wordpress;' | mysql -h mysql -u root -ppassword"

# Setup Docker container
docker-compose exec phpfpm bash -c "echo 'CREATE DATABASE ctoec;' | mysql -h mysql -u root -ppassword"
docker-compose exec phpfpm bash -c " echo \"CREATE USER 'wordpress'@'%' IDENTIFIED BY 'password';\" | mysql -h mysql -u root -ppassword"
docker-compose exec phpfpm bash -c "echo \" GRANT ALL PRIVILEGES ON  ctoec.* TO 'wordpress'@'%'; \" | mysql -h mysql -u root -ppassword"
docker run -it -u $(id -u):$(id -g) -v $(pwd):/wordpress 10up/phpfpm:7.3 bash -c "cd /wordpress && composer install"
docker-compose exec -u $(id -u):$(id -g) phpfpm bash -c 'wp config create --dbname=ctoec --dbuser=wordpress --dbhost=mysql --dbpass=password'
docker-compose exec phpfpm bash -c 'mysql -h mysql -u root -ppassword ctoec < /tmp/backup/backup.sql'
docker-compose exec phpfpm bash -c " echo \"USE ctoec; UPDATE wp_options SET option_value='http://localhost:8080' WHERE option_name ='home';\" | mysql -h mysql -u root -ppassword"
docker-compose exec phpfpm bash -c " echo \"USE ctoec; UPDATE wp_options SET option_value='http://localhost:8080' WHERE option_name ='siteurl';\" | mysql -h mysql -u root -ppassword"