#!/bin/sh
set -ex

docker-compose up -d

function dbIsDown { docker-compose exec phpfpm bash -c 'mysqladmin -h mysql -u root -ppassword status  > /dev/null 2>&1' && echo "$?"; }

while [ -z $(dbIsDown)  ]; do
    echo "waiting for mysql to start working"
    sleep 3s
done

echo "mysql is ready"
